import Head from 'next/head'
import { Scheduling } from '../../components/pages/Scheduling'

export default function SchedulingPage() {
  return (
    <>
      <Head>
        <title>Agendamento - Centro Pokémon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Scheduling />
    </>
  )
}
